In [346]:
import pandas as pd
import os

In [347]:
pokemon= pd.read_csv('pokemon.csv')

Este conjunto de datos contiene información sobre todos las 802 entradas de la Pokédex de
las primeras siete generaciones de Pokémon. La información contenida en este conjunto de
datos incluye estadísticas base, rendimiento frente a otros tipos, altura, peso, clasificación,
pasos de huevo,puntos de experiencia, habilidades, etc. La informacion se extrajo de
http://serebii.net/Serebi.net

In [348]:
pokemon

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

• name: El nombre en inglés del Pokémon.

• japanese name: El nombre japonés original del Pokémon.

• pokedex number: El número de entrada del Pokémon en la Pokédex Nacional.

• percentage male: El porcentaje de especies que son machos. En blanco si el Pokémon
no tiene género.

• type1: El tipo principal de Pokémon.

• type2: El tipo secundario de Pokémon.

• classification: La clasificación de los Pokémon tal como la describe el Pokedex de Sol y
Luna.

• height m: Altura del Pokémon en metros.

• weight kg: El peso del Pokémon en kilogramos.

• capture rate: Tasa de captura del Pokémon.

• baseeggsteps: El número de pasos necesarios para incubar un huevo del Pokémon.

• abilities: Una lista secuenciada de habilidades que el Pokémon es capaz de tener.

• experience growth: El crecimiento de la experiencia del Pokémon.

• base happiness: Felicidad básica del Pokémon.

• against_?: Dieciocho características que denotan la cantidad de daño recibido contra un
ataque de un tipo particular.

• hp: El HP base del Pokémon.

• attack: El ataque base de los Pokémon.

• defense: La defensa básica de los Pokémon.

• sp attack: El ataque especial básico del Pokémon.

• sp defense: La Defensa Especial Base del Pokémon.

• speed: La velocidad base del Pokémon.

• generation: La generación numerada en la que se introdujo por primera vez el Pokémon.

• is legendary: Indica si el Pokémon es legendario.

# Actividades
1. Genere el o los modelados de datos necesarios a partir de los datos propuestos,
considere el tema de calidad de datos en su modelado. Un ejemplo sería generar una vista
para comparar algunas características a partir del type1, piense en más de ellas. ¿Qué
sería lo más interesante a describir?

2. Genere un dashboard en alguna herramienta de BI de su preferencia a partir del conjunto
de datos proporcionado. ¿Cómo nos sirve este tablero para encontrar hallazgos
rápidamente en los datos? Un tablero puede servir para: Analizar, Buscar, Consultar. Según
el Modelo de Munzner la abstracción de tareas visuales corresponde a identificar pares de
acciones y objetivos, Tarea={Acción, Objetivo}:

# Entregables
Dashboard interactivo en alguna herramienta seleccionada. Se considera válida
la entrega de un video mostrando la funcionalidad, además adjuntar el script con el
modelado de datos desde Python y una imagen que muestre el diagrama de el/los modelos
de datos que son la base de su tablero.

In [349]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    object
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB

In [350]:
pokemon['name']

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
796    Celesteela
797       Kartana
798      Guzzlord
799      Necrozma
800      Magearna
Name: name, Length: 801, dtype: object

In [351]:
pokemon['name']

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
796    Celesteela
797       Kartana
798      Guzzlord
799      Necrozma
800      Magearna
Name: name, Length: 801, dtype: object

In [352]:
pokemon['japanese_name']

0      Fushigidaneフシギダネ
1       Fushigisouフシギソウ
2      Fushigibanaフシギバナ
3          Hitokageヒトカゲ
4           Lizardoリザード
             ...
796      Tekkaguyaテッカグヤ
797     Kamiturugiカミツルギ
798     Akuzikingアクジキング
799       Necrozmaネクロズマ
800        Magearnaマギアナ
Name: japanese_name, Length: 801, dtype: object

limpieza de capture_rate (str): 774

In [353]:
pokemon['capture_rate']#Podemos ver que los tipos de datos aparentan ser numericos, sin embargo no parece ser del todo asi

0       45
1       45
2       45
3       45
4       45
      ...
796     25
797    255
798     15
799      3
800      3
Name: capture_rate, Length: 801, dtype: object

In [354]:
pokemon['capture_rate'].unique()#Se ve que los valores son cadenas de numeros por lo que abra que pasar a tipo numerico

array(['45', '255', '120', '127', '90', '190', '75', '235', '150', '25',
       '170', '50', '200', '100', '180', '60', '225', '30', '35', '3',
       '65', '70', '125', '205', '155', '145', '130', '140', '15', '220',
       '160', '80', '55', '30 (Meteorite)255 (Core)'], dtype=object)

In [355]:
pokemon.loc[773,'capture_rate'] = '30'

In [356]:
pokemon[pokemon['pokedex_number']==774]['capture_rate']# Cambiamos el valor del indice 773

773    30
Name: capture_rate, dtype: object

In [357]:
df=pokemon.copy()

In [358]:
df[df['pokedex_number']==774]['capture_rate']

773    30
Name: capture_rate, dtype: object

In [359]:
pokemon_nulos=pokemon[pokemon['height_m'].isnull()]#Vemos que tenemos nulos en el peso
pokemon_nulos

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
18,"['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hu...",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,19,25,35,72,normal,dark,NaN,1,0
19,"['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hu...",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,20,40,80,77,normal,dark,NaN,1,0
25,"['Static', 'Lightningrod', 'Surge Surfer']",1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,50.0,26,95,85,110,electric,electric,NaN,1,0
26,"['Sand Veil', 'Sand Rush', 'Snow Cloak', 'Slus...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,27,10,35,40,ground,ice,NaN,1,0
27,"['Sand Veil', 'Sand Rush', 'Snow Cloak', 'Slus...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,28,25,65,65,ground,ice,NaN,1,0
36,"['Flash Fire', 'Drought', 'Snow Cloak', 'Snow ...",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,24.6,37,50,65,65,fire,ice,NaN,1,0
37,"['Flash Fire', 'Drought', 'Snow Cloak', 'Snow ...",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,24.6,38,81,100,109,fire,ice,NaN,1,0
49,"['Sand Veil', 'Arena Trap', 'Sand Force', 'San...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,50,35,45,90,ground,ground,NaN,1,0
50,"['Sand Veil', 'Arena Trap', 'Sand Force', 'San...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,51,50,70,110,ground,ground,NaN,1,0
51,"['Pickup', 'Technician', 'Unnerve', 'Pickup', ...",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,52,50,40,90,normal,dark,NaN,1,0
52,"['Limber', 'Technician', 'Unnerve', 'Fur Coat'...",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,53,75,65,115,normal,dark,NaN,1,0
73,"['Rock Head', 'Sturdy', 'Sand Veil', 'Magnet P...",1.0,1.0,1.0,0.0,1.0,2.0,0.5,0.5,1.0,...,50.0,74,30,30,20,rock,ground,NaN,1,0
74,"['Rock Head', 'Sturdy', 'Sand Veil', 'Magnet P...",1.0,1.0,1.0,0.0,1.0,2.0,0.5,0.5,1.0,...,50.0,75,45,45,35,rock,ground,NaN,1,0
75,"['Rock Head', 'Sturdy', 'Sand Veil', 'Magnet P...",1.0,1.0,1.0,0.0,1.0,2.0,0.5,0.5,1.0,...,50.0,76,55,65,45,rock,ground,NaN,1,0
87,"['Stench', 'Sticky Hold', 'Poison Touch', 'Poi...",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,88,40,50,25,poison,poison,NaN,1,0
88,"['Stench', 'Sticky Hold', 'Poison Touch', 'Poi...",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,89,65,100,50,poison,poison,NaN,1,0
102,"['Chlorophyll', 'Harvest', 'Frisk', 'Harvest']",4.0,2.0,1.0,0.5,1.0,0.5,2.0,2.0,2.0,...,50.0,103,125,75,45,grass,psychic,NaN,1,0
104,"['Rock Head', 'Lightningrod', 'Battle Armor', ...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,105,50,80,45,ground,fire,NaN,1,0
719,['Magician'],1.0,4.0,1.0,1.0,1.0,0.0,1.0,1.0,4.0,...,NaN,720,170,130,80,psychic,ghost,NaN,6,1
744,"['Keen Eye', 'Sand Rush', 'Steadfast', 'Keen E...",1.0,1.0,1.0,1.0,1.0,2.0,0.5,0.5,1.0,...,50.0,745,55,75,82,rock,NaN,NaN,7,0

In [360]:
df.at[18, 'weight_kg'] = 3.5
df.at[18, 'height_m'] = 1.1 #Agregamos los valores faltantes que se consiguieron en internet

df.at[19, 'weight_kg'] = 3.2
df.at[19, 'height_m'] = 0.7

df.at[25, 'weight_kg'] = 6.0
df.at[25, 'height_m'] = 0.4

df.at[26, 'weight_kg'] = 30.0
df.at[26, 'height_m'] = 0.8

df.at[27, 'weight_kg'] = 12.0
df.at[27, 'height_m'] = 0.6

df.at[36, 'weight_kg'] = 34.0
df.at[36, 'height_m'] = 1.0

df.at[37, 'weight_kg'] = 9.9
df.at[37, 'height_m'] = 0.6

df.at[49, 'weight_kg'] = 12.5
df.at[49, 'height_m'] = 1.5

df.at[50, 'weight_kg'] = 0.8
df.at[50, 'height_m'] = 0.2

df.at[51, 'weight_kg'] = 33.3
df.at[51, 'height_m'] = 0.7

df.at[52, 'weight_kg'] = 4.2
df.at[52, 'height_m'] = 0.4

df.at[73, 'weight_kg'] = 55.0
df.at[73, 'height_m'] = 1.6

df.at[74, 'weight_kg'] = 20.0
df.at[74, 'height_m'] = 0.4

df.at[75, 'weight_kg'] = 105.0
df.at[75, 'height_m'] = 1.0

df.at[87, 'weight_kg'] = 120.0
df.at[87, 'height_m'] = 1.7

df.at[88, 'weight_kg'] = 30.0
df.at[88, 'height_m'] = 0.9

df.at[102, 'weight_kg'] = 2.5
df.at[102, 'height_m'] = 0.4

df.at[104, 'weight_kg'] = 6.5
df.at[104, 'height_m'] = 0.4

df.at[719, 'weight_kg'] = 25.0
df.at[719, 'height_m'] = 0.7

df.at[744, 'weight_kg'] = 9.2
df.at[744, 'height_m'] = 0.5

In [361]:
df['weight_kg'].isnull().sum()

np.int64(0)

In [362]:
df['height_m'].isnull().sum()# Comprobamso que no hay valores nulos

np.int64(0)

In [363]:
pokemon['type1'].unique()# Para hacer la tabla de indices en el tipo tenemos que identificar los valores unicos de la columna

array(['grass', 'fire', 'water', 'bug', 'normal', 'poison', 'electric',
       'ground', 'fairy', 'fighting', 'psychic', 'rock', 'ghost', 'ice',
       'dragon', 'dark', 'steel', 'flying'], dtype=object)

In [364]:
df['capture_rate'] = pd.to_numeric(df['capture_rate'], errors='coerce')# Cambiamos las cadenas a valores numericos de la columna capture_rate

In [365]:
df.info() #Comprobamos el valor numerico

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    int64
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           801 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          801 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(14), object(6)
memory usage: 256.7+ KB

In [366]:
type_equal = df[df['type1'] == df['type2']]# Se ve que hay tipos de pokemon que se repiten
type_equal

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
25,"['Static', 'Lightningrod', 'Surge Surfer']",1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,50.0,26,95,85,110,electric,electric,6.0,1,0
49,"['Sand Veil', 'Arena Trap', 'Sand Force', 'San...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,50,35,45,90,ground,ground,12.5,1,0
50,"['Sand Veil', 'Arena Trap', 'Sand Force', 'San...",1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,50.0,51,50,70,110,ground,ground,0.8,1,0
87,"['Stench', 'Sticky Hold', 'Poison Touch', 'Poi...",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,88,40,50,25,poison,poison,120.0,1,0
88,"['Stench', 'Sticky Hold', 'Poison Touch', 'Poi...",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,89,65,100,50,poison,poison,30.0,1,0
491,"['Natural Cure', 'Serene Grace']",2.0,1.0,1.0,0.5,1.0,1.0,2.0,2.0,1.0,...,NaN,492,120,75,127,grass,grass,2.1,4,1
554,"['Sheer Force', 'Zen Mode']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,50.0,555,140,105,55,fire,fire,92.9,5,0

Combinaciones de types
- Renombrar types (con numeros)
-Concatenar
type_id

In [367]:
df['type1'].unique()

array(['grass', 'fire', 'water', 'bug', 'normal', 'poison', 'electric',
       'ground', 'fairy', 'fighting', 'psychic', 'rock', 'ghost', 'ice',
       'dragon', 'dark', 'steel', 'flying'], dtype=object)

In [368]:
df['type2'].unique()# Identifiamos nan en esta columna

array(['poison', nan, 'flying', 'dark', 'electric', 'ice', 'ground',
       'fairy', 'grass', 'fighting', 'psychic', 'steel', 'fire', 'rock',
       'water', 'dragon', 'ghost', 'bug', 'normal'], dtype=object)

In [369]:
df['type2'] = df['type2'].fillna(df['type1']) #Llenamos los valores nan con su correspondiente en el type1 que no tiene nulos

In [370]:
df[(df['type1']==df['type2']) & (df['name']=='Charmander')]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,fire,8.5,1,0

In [371]:
df[(df['type1']==df['type2'])]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,fire,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,fire,19.0,1,0
6,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,water,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,water,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,water,85.5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,"['Bulletproof', 'Soundproof', 'Overcoat']",1.0,1.0,2.0,0.5,2.0,1.0,0.5,1.0,1.0,...,50.0,782,45,45,45,dragon,dragon,29.7,7,0
788,['Unaware'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,789,29,31,37,psychic,psychic,0.1,7,1
789,['Sturdy'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,790,29,131,37,psychic,psychic,999.9,7,1
795,['Beast Boost'],1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,NaN,796,173,71,83,electric,electric,100.0,7,1
799,['Prism Armor'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,psychic,230.0,7,1

In [372]:
df[(df['type1'] == 'normal') & (df['type2'] == 'flying')]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
15,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,16,35,35,56,normal,flying,1.8,1,0
16,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,17,50,50,71,normal,flying,30.0,1,0
17,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,18,135,80,121,normal,flying,39.5,1,0
20,"['Keen Eye', 'Sniper']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,21,31,31,70,normal,flying,2.0,1,0
21,"['Keen Eye', 'Sniper']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,22,61,61,100,normal,flying,38.0,1,0
82,"['Keen Eye', 'Inner Focus', 'Defiant']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,83,58,62,60,normal,flying,15.0,1,0
83,"['Run Away', 'Early Bird', 'Tangled Feet']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,84,35,35,75,normal,flying,39.2,1,0
84,"['Run Away', 'Early Bird', 'Tangled Feet']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,85,60,60,110,normal,flying,85.2,1,0
162,"['Insomnia', 'Keen Eye', 'Tinted Lens']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,163,36,56,50,normal,flying,21.2,2,0
163,"['Insomnia', 'Keen Eye', 'Tinted Lens']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,164,86,96,70,normal,flying,40.8,2,0
275,"['Guts', 'Scrappy']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,276,30,30,85,normal,flying,2.3,3,0
276,"['Guts', 'Scrappy']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,277,75,50,125,normal,flying,19.8,3,0
332,"['Natural Cure', 'Cloud Nine']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,333,40,75,50,normal,flying,1.2,3,0
395,"['Keen Eye', 'Reckless']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,396,30,30,60,normal,flying,2.0,4,0
396,"['Intimidate', 'Reckless']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,397,40,40,80,normal,flying,15.5,4,0
397,"['Intimidate', 'Reckless']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,398,50,60,100,normal,flying,24.9,4,0
440,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,441,92,42,91,normal,flying,1.9,4,0
518,"['Big Pecks', 'Super Luck', 'Rivalry']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,519,36,30,43,normal,flying,2.1,5,0
519,"['Big Pecks', 'Super Luck', 'Rivalry']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,520,50,42,65,normal,flying,15.0,5,0
520,"['Big Pecks', 'Super Luck', 'Rivalry']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,521,65,55,93,normal,flying,29.0,5,0
626,"['Keen Eye', 'Sheer Force', 'Hustle']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,100.0,627,37,50,60,normal,flying,10.5,5,0
627,"['Keen Eye', 'Sheer Force', 'Defiant']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,100.0,628,57,75,80,normal,flying,41.0,5,0
660,"['Big Pecks', 'Gale Wings']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,661,40,38,62,normal,flying,1.7,6,0
730,"['Keen Eye', 'Skill Link', 'Pickup']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,731,30,30,65,normal,flying,1.2,7,0
731,"['Keen Eye', 'Skill Link', 'Pickup']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,732,40,50,75,normal,flying,14.8,7,0
732,"['Keen Eye', 'Skill Link', 'Sheer Force']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,733,75,75,60,normal,flying,26.0,7,0

In [373]:
len(df['type1'].unique())#Comparamos el tamaño de valores unicos de los tipos de pokemon

18

In [374]:
len(df['type2'].unique())

18

In [375]:
type_df = pd.concat([df['type1'], df['type2']]).unique()# Convinamos las dos columnas de tipos en un solo dataframe

In [376]:
len(type_df)

18

In [377]:
mapping = {category: idx for idx, category in enumerate(type_df)}#Hacemos un mapeo de los tipos de pokemon y lps enumeramos

In [378]:
df['type1_ID'] = df['type1'].map(mapping)#Con el mapeo asignamos un valor numerico o ID a los tipos de pokemon

In [379]:
df['type2_ID'] = df['type2'].map(mapping)

In [380]:
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,type1_ID,type2_ID
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,65,65,45,grass,poison,6.9,1,0,0,5
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,80,80,60,grass,poison,13.0,1,0,0,5
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,122,120,80,grass,poison,100.0,1,0,0,5
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,60,50,65,fire,fire,8.5,1,0,1,1
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,80,65,80,fire,fire,19.0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,107,101,61,steel,flying,999.9,7,1,16,17
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,59,31,109,grass,steel,0.1,7,1,0,16
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,97,53,43,dark,dragon,888.0,7,1,15,14
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,127,89,79,psychic,psychic,230.0,7,1,10,10
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,130,115,65,steel,fairy,80.5,7,1,16,8

In [381]:
type_equal = df[df['type1'] == df['type2']]# Confirmamos que se asignaron correctamente los IDs
type_equal

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,type1_ID,type2_ID
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,60,50,65,fire,fire,8.5,1,0,1,1
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,80,65,80,fire,fire,19.0,1,0,1,1
6,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,50,64,43,water,water,9.0,1,0,2,2
7,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,65,80,58,water,water,22.5,1,0,2,2
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,135,115,78,water,water,85.5,1,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,"['Bulletproof', 'Soundproof', 'Overcoat']",1.0,1.0,2.0,0.5,2.0,1.0,0.5,1.0,1.0,...,45,45,45,dragon,dragon,29.7,7,0,14,14
788,['Unaware'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,29,31,37,psychic,psychic,0.1,7,1,10,10
789,['Sturdy'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,29,131,37,psychic,psychic,999.9,7,1,10,10
795,['Beast Boost'],1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,173,71,83,electric,electric,100.0,7,1,6,6
799,['Prism Armor'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,127,89,79,psychic,psychic,230.0,7,1,10,10

In [382]:
unique_v = pd.unique(df['type1_ID'].values.ravel())

In [383]:
unique_v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [384]:
unique_vtype = pd.unique(df['type1'].values.ravel())

In [385]:
unique_vtype

array(['grass', 'fire', 'water', 'bug', 'normal', 'poison', 'electric',
       'ground', 'fairy', 'fighting', 'psychic', 'rock', 'ghost', 'ice',
       'dragon', 'dark', 'steel', 'flying'], dtype=object)

In [386]:
td_pokemon_type = pd.DataFrame({'type_ID':unique_v[:len(unique_v)],'type': unique_vtype[:len(unique_vtype)]})# Creamos la tabla de dimensiones

In [387]:
df.drop(columns=['type1','type2'],inplace = True)

In [388]:
df.isnull().sum() #Comprobamos donde hay nulos

abilities             0
against_bug           0
against_dark          0
against_dragon        0
against_electric      0
against_fairy         0
against_fight         0
against_fire          0
against_flying        0
against_ghost         0
against_grass         0
against_ground        0
against_ice           0
against_normal        0
against_poison        0
against_psychic       0
against_rock          0
against_steel         0
against_water         0
attack                0
base_egg_steps        0
base_happiness        0
base_total            0
capture_rate          0
classfication         0
defense               0
experience_growth     0
height_m              0
hp                    0
japanese_name         0
name                  0
percentage_male      98
pokedex_number        0
sp_attack             0
sp_defense            0
speed                 0
weight_kg             0
generation            0
is_legendary          0
type1_ID              0
type2_ID              0
dtype: int64

In [389]:
# Podemos ver que hay una columna que tiene datos faltantes, sin embargo debido al numero de datos que faltan, a la especificidad de estos y
# sobre todo a que no se tiene mucha relevancia para nuestras metricas de la tabla de hechos podemos prescindir de esta columna
df.drop(columns ='percentage_male', inplace = True)

In [390]:
df.isnull().sum() #Comprobamos donde hay nulos

abilities            0
against_bug          0
against_dark         0
against_dragon       0
against_electric     0
against_fairy        0
against_fight        0
against_fire         0
against_flying       0
against_ghost        0
against_grass        0
against_ground       0
against_ice          0
against_normal       0
against_poison       0
against_psychic      0
against_rock         0
against_steel        0
against_water        0
attack               0
base_egg_steps       0
base_happiness       0
base_total           0
capture_rate         0
classfication        0
defense              0
experience_growth    0
height_m             0
hp                   0
japanese_name        0
name                 0
pokedex_number       0
sp_attack            0
sp_defense           0
speed                0
weight_kg            0
generation           0
is_legendary         0
type1_ID             0
type2_ID             0
dtype: int64

In [391]:
df.nunique()

abilities            482
against_bug            5
against_dark           5
against_dragon         4
against_electric       6
against_fairy          5
against_fight          6
against_fire           5
against_flying         5
against_ghost          5
against_grass          5
against_ground         6
against_ice            5
against_normal         4
against_poison         6
against_psychic        6
against_rock           5
against_steel          5
against_water          5
attack               114
base_egg_steps        10
base_happiness         6
base_total           203
capture_rate          33
classfication        588
defense              109
experience_growth      6
height_m              51
hp                    99
japanese_name        801
name                 801
pokedex_number       801
sp_attack            111
sp_defense            97
speed                113
weight_kg            421
generation             7
is_legendary           2
type1_ID              18
type2_ID              18
dtype: int64

In [392]:
td_pokemon_info = pd.DataFrame({ #Creamos la tabla de dimensiones 'td_pokemon_info'
    'pokedex_number': df['pokedex_number'],
    'name': df['name'],
    'japanese_name': df['japanese_name'],
    'generation': df['generation'],
    'is_legendary': df['is_legendary'],
    'height_m': df['height_m'],
    'weight_kg': df['weight_kg'],
    'base_egg_steps': df['base_egg_steps'],
    'capture_rate': df['capture_rate'],
    'classfication': df['classfication'],
    'abilities': df['abilities'],
    'base_happiness' : df['base_happiness'],
    'experience_growth' : df['experience_growth']
    
})

In [393]:
df.drop(columns=['name','japanese_name','generation','is_legendary','height_m','weight_kg','base_egg_steps','capture_rate','classfication','abilities','base_happiness','experience_growth'],inplace = True)
#Sacamos del df las columnas de los valores que esta en la tabla de dimensiones

In [394]:
df

,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,...,attack,base_total,defense,hp,pokedex_number,sp_attack,sp_defense,speed,type1_ID,type2_ID
0,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,...,49,318,49,45,1,65,65,45,0,5
1,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,...,62,405,63,60,2,80,80,60,0,5
2,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,...,100,625,123,80,3,122,120,80,0,5
3,0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,...,52,309,43,39,4,60,50,65,1,1
4,0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,...,64,405,58,58,5,80,65,80,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,0.25,...,101,570,103,97,797,107,101,61,16,17
797,1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,0.25,...,181,570,131,59,798,59,31,109,0,16
798,2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,0.50,...,101,570,53,223,799,97,53,43,15,14
799,2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,1.00,...,107,600,101,97,800,127,89,79,10,10
800,0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,0.50,...,95,600,115,80,801,130,115,65,16,8

In [395]:
td_against_types = pd.DataFrame({# Creamos otra tabla de dimesniones
    'type1_ID': df['type1_ID'],  
    'type2_ID': df['type2_ID'],  
    'against_bug': df['against_bug'],           
    'against_dark': df['against_dark'],         
    'against_dragon': df['against_dragon'],     
    'against_electric': df['against_electric'], 
    'against_fairy': df['against_fairy'],       
    'against_fight': df['against_fight'],       
    'against_fire': df['against_fire'],         
    'against_flying': df['against_flying'],     
    'against_ghost': df['against_ghost'],       
    'against_grass': df['against_grass'],       
    'against_ground': df['against_ground'],     
    'against_ice': df['against_ice'],           
    'against_normal': df['against_normal'],     
    'against_poison': df['against_poison'],     
    'against_psychic': df['against_psychic'],   
    'against_rock': df['against_rock'],         
    'against_steel': df['against_steel'],       
    'against_water': df['against_water']
})

In [396]:
td_against_types = td_against_types.drop_duplicates(subset=['type1_ID', 'type2_ID']).reset_index(drop=True) # Nos quedamos con los valores unicos

In [397]:
df = df.drop(columns=df.filter(regex='against').columns)

In [398]:
df

,attack,base_total,defense,hp,pokedex_number,sp_attack,sp_defense,speed,type1_ID,type2_ID
0,49,318,49,45,1,65,65,45,0,5
1,62,405,63,60,2,80,80,60,0,5
2,100,625,123,80,3,122,120,80,0,5
3,52,309,43,39,4,60,50,65,1,1
4,64,405,58,58,5,80,65,80,1,1
...,...,...,...,...,...,...,...,...,...,...
796,101,570,103,97,797,107,101,61,16,17
797,181,570,131,59,798,59,31,109,0,16
798,101,570,53,223,799,97,53,43,15,14
799,107,600,101,97,800,127,89,79,10,10
800,95,600,115,80,801,130,115,65,16,8

In [402]:
th_pokemon_stats = df.copy() #Finalmente se crea la tabla de facts o hechos a partir del dataframe original

# Modelos de datos

th_pokemon_stats 
td_pokemon_info 
td_against_types 
td_type

## td_pokemon_info

    pokedex_number
    name
    japanese_name
    generation
    is_legendary
    height_m
    weight_kg
    base_egg_steps
    capture_rate
    classification
    abilities
    base_happiness
    experience_growth

In [399]:
td_pokemon_info

,pokedex_number,name,japanese_name,generation,is_legendary,height_m,weight_kg,base_egg_steps,capture_rate,classfication,abilities,base_happiness,experience_growth
0,1,Bulbasaur,Fushigidaneフシギダネ,1,0,0.7,6.9,5120,45,Seed Pokémon,"['Overgrow', 'Chlorophyll']",70,1059860
1,2,Ivysaur,Fushigisouフシギソウ,1,0,1.0,13.0,5120,45,Seed Pokémon,"['Overgrow', 'Chlorophyll']",70,1059860
2,3,Venusaur,Fushigibanaフシギバナ,1,0,2.0,100.0,5120,45,Seed Pokémon,"['Overgrow', 'Chlorophyll']",70,1059860
3,4,Charmander,Hitokageヒトカゲ,1,0,0.6,8.5,5120,45,Lizard Pokémon,"['Blaze', 'Solar Power']",70,1059860
4,5,Charmeleon,Lizardoリザード,1,0,1.1,19.0,5120,45,Flame Pokémon,"['Blaze', 'Solar Power']",70,1059860
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,797,Celesteela,Tekkaguyaテッカグヤ,7,1,9.2,999.9,30720,25,Launch Pokémon,['Beast Boost'],0,1250000
797,798,Kartana,Kamiturugiカミツルギ,7,1,0.3,0.1,30720,255,Drawn Sword Pokémon,['Beast Boost'],0,1250000
798,799,Guzzlord,Akuzikingアクジキング,7,1,5.5,888.0,30720,15,Junkivore Pokémon,['Beast Boost'],0,1250000
799,800,Necrozma,Necrozmaネクロズマ,7,1,2.4,230.0,30720,3,Prism Pokémon,['Prism Armor'],0,1250000
800,801,Magearna,Magearnaマギアナ,7,1,1.0,80.5,30720,3,Artificial Pokémon,['Soul-Heart'],0,1250000

## th_pokemon_stats

    pokedex_number
    type_id
    base_total
    attack
    defense
    sp_attack
    sp_defense
    speed
    hp

In [403]:
th_pokemon_stats

,attack,base_total,defense,hp,pokedex_number,sp_attack,sp_defense,speed,type1_ID,type2_ID
0,49,318,49,45,1,65,65,45,0,5
1,62,405,63,60,2,80,80,60,0,5
2,100,625,123,80,3,122,120,80,0,5
3,52,309,43,39,4,60,50,65,1,1
4,64,405,58,58,5,80,65,80,1,1
...,...,...,...,...,...,...,...,...,...,...
796,101,570,103,97,797,107,101,61,16,17
797,181,570,131,59,798,59,31,109,0,16
798,101,570,53,223,799,97,53,43,15,14
799,107,600,101,97,800,127,89,79,10,10
800,95,600,115,80,801,130,115,65,16,8

## td_pokemon_type

    type_id
    type1
    type2

In [400]:
td_pokemon_type

    type_ID      type
0         0     grass
1         1      fire
2         2     water
3         3       bug
4         4    normal
5         5    poison
6         6  electric
7         7    ground
8         8     fairy
9         9  fighting
10       10   psychic
11       11      rock
12       12     ghost
13       13       ice
14       14    dragon
15       15      dark
16       16     steel
17       17    flying

## td_against_types

    type_id
    against_bug            
    against_dark           
    against_dragon         
    against_electric       
    against_fairy          
    against_fight          
    against_fire           
    against_flying         
    against_ghost          
    against_grass          
    against_ground         
    against_ice            
    against_normal         
    against_poison         
    against_psychic        
    against_rock           
    against_steel          
    against_water

In [401]:
td_against_types

,type1_ID,type2_ID,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water
0,0,5,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.00,2.00,1.0,1.0,0.5
1,1,1,0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.00,1.00,2.0,0.5,2.0
2,1,17,0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,0.25,0.0,1.0,1.0,1.00,1.00,4.0,0.5,2.0
3,2,2,1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,2.00,1.0,0.5,1.0,1.00,1.00,1.0,0.5,0.5
4,3,3,1.00,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,0.50,0.5,1.0,1.0,1.00,1.00,2.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,12,8,0.25,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,1.00,1.0,1.0,0.0,1.00,1.00,1.0,2.0,1.0
157,4,14,1.00,1.0,2.0,0.5,2.0,2.0,0.5,1.0,0.0,0.50,1.0,2.0,1.0,1.00,1.00,1.0,1.0,0.5
158,14,9,0.50,0.5,2.0,0.5,4.0,1.0,0.5,2.0,1.0,0.50,1.0,2.0,1.0,1.00,2.00,0.5,1.0,0.5
159,10,16,1.00,2.0,0.5,1.0,0.5,1.0,2.0,0.5,2.0,0.50,2.0,0.5,0.5,0.00,0.25,0.5,0.5,1.0
160,11,5,0.50,1.0,1.0,1.0,0.5,1.0,0.5,0.5,1.0,1.00,4.0,1.0,0.5,0.25,2.00,1.0,2.0,2.0

In [407]:
th_pokemon_stats.to_csv('th_pokemon_stats', index = False) #Se pasan a csv para poder hacer el tablero
td_against_types.to_csv('td_against_types',index=False)
td_pokemon_type.to_csv('td_pokemon_type', index = False)
td_pokemon_info.to_csv('td_pokemon_info', index = False)